#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

test_fmt() {
  hash gofmt 2>&- || { printf >&2 "${RED}gofmt not in PATH.${NC}\n"; exit 1; }
  IFS='
  '
  for file in `git diff --cached --name-only --diff-filter=ACM | grep '\.go$'`
  do
    output=`git cat-file -p :$file | gofmt -l 2>&1`
    if test $? -ne 0
    then
      output=`echo "$output" | sed "s,<standard input>,$file,"`
      syntaxerrors="${list}${output}\n"
    elif test -n "$output"
    then
      list="${list}${file}\n"
    fi
  done
  exitcode=0
  if test -n "$syntaxerrors"
  then
    printf >&2 "${RED}gofmt found syntax errors:${NC}\n"
    printf "$syntaxerrors"
    exitcode=1
  fi
  if test -n "$list"
  then
    printf >&2 "${RED}gofmt needs to format these files (run gofmt -w and git add):${NC}\n"
    printf "$list"
    exitcode=1
  fi
  exit $exitcode
}

if [ -f go.mod ]; then
  case "$1" in
    --about )
      echo "Check Go code formatting"
      ;;
    * )
      test_fmt
      ;;
  esac
fi

